# Generated by Django 4.0.5 on 2022-08-22 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=10)),
                ('is_present', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.date(2022, 8, 21))),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_subjects', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('assignedClass', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('teacher_residence', models.CharField(max_length=250)),
                ('subject', models.ManyToManyField(to='mySchoolapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
                ('subject_topics_file', models.FileField(upload_to='media')),
                ('teacher_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.teacherdetails', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('student_residence', models.CharField(max_length=250)),
                ('added_subject', models.ManyToManyField(to='mySchoolapp.subjects')),
                ('teacher_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.teacherdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ClassesAndSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
                ('class_major_subjects', models.ManyToManyField(to='mySchoolapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('other_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=8)),
                ('position', models.CharField(max_length=150)),
                ('residence', models.CharField(max_length=150)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('student_class', models.CharField(max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
