# Generated by Django 4.0.5 on 2022-08-22 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 22)),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='added_subject',
            field=models.ManyToManyField(blank=True, null=True, to='mySchoolapp.subjects'),
        ),
    ]
