# Generated by Django 4.0.5 on 2022-08-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0002_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='student_class',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
