# Generated by Django 4.0.5 on 2022-08-24 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0003_studentdetails_student_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='added_subject',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 23)),
        ),
    ]
