# Generated by Django 4.0.5 on 2022-08-27 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0004_rename_added_subject_studentdetails_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_details', models.TextField(max_length=1000)),
                ('announcement_date', models.DateTimeField()),
                ('announcement_deadline', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 27)),
        ),
    ]
