# Generated by Django 4.0.5 on 2022-08-29 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0005_announcement_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='user_slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 28)),
        ),
    ]
