# Generated by Django 4.0.5 on 2022-08-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0006_studentdetails_user_slug_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='user_slug',
            new_name='student_slug',
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='teacher_slug',
            field=models.SlugField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
