# Generated by Django 4.0.5 on 2022-08-30 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0007_rename_user_slug_studentdetails_student_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherdetails',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 30)),
        ),
    ]
