# Generated by Django 4.0.5 on 2022-08-31 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0008_rename_subject_teacherdetails_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectfile',
            name='subject_topics_file',
        ),
        migrations.AddField(
            model_name='subjectfile',
            name='subject_files',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 31)),
        ),
    ]
