# Generated by Django 4.0.5 on 2022-09-05 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0010_subjectfile_subject_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_week', models.CharField(max_length=20)),
                ('subject_files', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 5)),
        ),
    ]
