# Generated by Django 4.0.5 on 2022-09-07 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0012_rename_subject_files_assignmentfiles_subject_assignment_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentFiles',
        ),
        migrations.AddField(
            model_name='subjectfile',
            name='kind_of_file',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 6)),
        ),
    ]
