# Generated by Django 4.0.5 on 2022-09-18 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0013_delete_assignmentfiles_subjectfile_kind_of_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectFile',
            new_name='Assignments',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 18)),
        ),
        migrations.CreateModel(
            name='SubjectNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_file', models.CharField(max_length=20)),
                ('week', models.CharField(max_length=10)),
                ('subject_files', models.FileField(upload_to='')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.subjects')),
                ('teacher_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.teacherdetails', to_field='email')),
            ],
        ),
    ]
