# Generated by Django 4.0.5 on 2022-09-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0014_rename_subjectfile_assignments_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectNotes',
            new_name='SubjectFile',
        ),
        migrations.DeleteModel(
            name='Assignments',
        ),
    ]
