# Generated by Django 4.0.5 on 2022-09-20 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0015_rename_subjectnotes_subjectfile_delete_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 20)),
        ),
    ]
