# Generated by Django 4.0.5 on 2022-09-21 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0016_subjectfile_title_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 21)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('commenter_name', models.CharField(max_length=50)),
                ('subject_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.subjectfile')),
            ],
        ),
    ]
