# Generated by Django 4.0.5 on 2022-09-26 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0017_alter_attendance_date_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectfile',
            old_name='title',
            new_name='file_title',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 25)),
        ),
    ]
