# Generated by Django 4.0.5 on 2022-10-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0019_alter_attendance_date_assignmentsolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsolution',
            old_name='student_name',
            new_name='student_email',
        ),
    ]
