# Generated by Django 4.0.5 on 2022-10-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0021_assignmentsolution_score_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsolution',
            name='number_of_submission',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
