# Generated by Django 4.0.5 on 2022-10-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0023_alter_assignmentsolution_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsolution',
            name='number_of_submission',
            field=models.IntegerField(null=True),
        ),
    ]
