# Generated by Django 4.0.5 on 2022-10-03 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0024_alter_assignmentsolution_number_of_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsolution',
            old_name='assignment_solution_file',
            new_name='solution_file',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 3)),
        ),
    ]
