# Generated by Django 4.0.5 on 2022-10-07 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0026_alter_assignmentsolution_number_of_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsolution',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 7)),
        ),
    ]
