# Generated by Django 4.0.5 on 2022-10-09 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0027_alter_assignmentsolution_score_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 22, 9, 53, 726702)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 8)),
        ),
    ]
