# Generated by Django 4.0.5 on 2022-10-09 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0028_subjectfile_date_uploaded_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='deadline_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subjectfile',
            name='deadline_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 22, 11, 11, 948116)),
        ),
    ]
