# Generated by Django 4.0.5 on 2022-10-10 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0030_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 22, 18, 19, 673549)),
        ),
    ]
