# Generated by Django 4.0.5 on 2022-10-11 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0032_sessioninfo_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='current_term',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 20, 27, 24, 674568)),
        ),
    ]
