# Generated by Django 4.0.5 on 2022-10-11 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0033_sessioninfo_current_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='current_term',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 21, 22, 42, 333461)),
        ),
    ]
