# Generated by Django 4.0.5 on 2022-10-11 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0035_alter_sessioninfo_current_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 23, 18, 1, 305778)),
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('term_starts', models.DateTimeField()),
                ('term_ends', models.DateTimeField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.sessioninfo')),
            ],
        ),
    ]
