# Generated by Django 4.0.5 on 2022-10-12 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0036_alter_subjectfile_date_uploaded_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 11)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 22, 56, 36, 396209)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.sessioninfo'),
        ),
    ]
