# Generated by Django 4.0.5 on 2022-10-12 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0037_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.sessioninfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 6, 3, 57, 580442)),
        ),
    ]
