# Generated by Django 4.0.5 on 2022-10-15 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0039_teacherdetails_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='start_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 19, 18, 19, 803028)),
        ),
    ]
