# Generated by Django 4.0.5 on 2022-10-15 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0040_terms_start_term_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terms',
            old_name='start_term',
            new_name='active_term',
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 22, 14, 45, 538696)),
        ),
    ]
