# Generated by Django 4.0.5 on 2022-11-05 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0041_rename_start_term_terms_active_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.terms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 11, 5)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 15, 48, 902158)),
        ),
    ]
