# Generated by Django 4.0.5 on 2022-11-05 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0042_subjectfile_term_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectfile',
            name='term',
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 19, 49, 985253)),
        ),
    ]
