# Generated by Django 4.0.5 on 2022-11-05 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0043_remove_subjectfile_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 23, 5, 785830)),
        ),
    ]
