# Generated by Django 4.0.5 on 2022-11-05 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0045_alter_subjectfile_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 8, 50, 2, 93488)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 5, 8, 50, 2, 93488), null=True),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 11, 5, 8, 50, 2, 93488), null=True),
        ),
    ]
