# Generated by Django 4.0.5 on 2022-11-05 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0046_alter_subjectfile_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mySchoolapp.terms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 9, 39, 31, 137525)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 5, 9, 39, 31, 137525), null=True),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 11, 5, 9, 39, 31, 137525), null=True),
        ),
    ]
