# Generated by Django 4.0.5 on 2022-11-30 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0047_subjectfile_term_alter_subjectfile_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='is_session_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 11, 29)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 50, 2, 585020)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 15, 50, 2, 585020), null=True),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 11, 29, 15, 50, 2, 585020), null=True),
        ),
    ]
