# Generated by Django 4.0.5 on 2022-12-04 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0048_sessioninfo_is_session_active_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 12, 4)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 12, 13, 36, 328916)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 4, 12, 13, 36, 328916), null=True),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 4, 12, 13, 36, 328916), null=True),
        ),
    ]
