# Generated by Django 4.0.5 on 2022-12-05 01:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolapp', '0049_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='teacher_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mySchoolapp.teacherdetails'),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 14, 22, 17, 985215)),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 4, 14, 22, 17, 985215), null=True),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='deadline_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 4, 14, 22, 17, 985215), null=True),
        ),
    ]
